### ISSUE TITLE
police alert

### ISSUE THREAD

**Issue by ScaryWolfies** [Z3R0L0G1C/zc-aitaxi#1]
hello, love the script, only 1 problem, everytime i get into the taxi, i get a police alert of car jacking, any idea how to fix it ? thank you

**Comment by Z3R0L0G1C** [comment]
Can you upload a screenshot of the notification you are getting here please, do you have any other scripts running that could be causing this to happen? Based on a default qb-core install which is what I tested this with, that doesn't occur. I'd be happy to assist you in fixing the issue though.

**Comment by ScaryWolfies** [comment]
![image](https://github.com/user-attachments/assets/291e78d7-51c7-4048-93d1-8895f7e940b1)
i'm using ps-dispatch and ps-mdt and everytime i step into the taxi i get the police alert of car jacking

**Comment by Z3R0L0G1C** [comment]
Go into, ps-dispatch/client/eventhandlers.lua

Change 
`AddEventHandler('CEventPedJackingMyVehicle', function(_, ped)
    WaitTimer('Autotheft', function()
        if cache.ped ~= ped then return end
        local vehicle = GetVehiclePedIsUsing(ped, true)
        exports['ps-dispatch']:CarJacking(vehicle)
    end)
end)`

to 
`AddEventHandler('CEventPedJackingMyVehicle', function(_, ped)
    WaitTimer('Autotheft', function()
        if cache.ped ~= ped then return end
        local vehicle = GetVehiclePedIsUsing(ped, true)
           if(vehicle == -956048545) then
           return end
           exports['ps-dispatch']:CarJacking(vehicle)
    end)
end)`

I think this should work, but I can not test please let me know.

**Comment by ScaryWolfies** [comment]
didnt work and i dont have the first code you wrote i have this

AddEventHandler('CEventPedJackingMyVehicle', function(_, ped)
    WaitTimer('Autotheft', function()
        if cache.ped ~= ped then return end
        local vehicle = GetVehiclePedIsUsing(ped, true)
        exports['ps-dispatch']:CarJacking(vehicle)
    end)
end)

i replaced it with the code you gave me and i still get the alert

**Comment by Z3R0L0G1C** [comment]
Try this one

AddEventHandler('CEventPedJackingMyVehicle', function(_, ped)
WaitTimer('Autotheft', function()
if cache.ped ~= ped then return end
local vehicle = GetVehiclePedIsUsing(ped, true)
local vehModel = GetEntityModel(vehicle)
 if(vehModel == -956048545) then return end
else 
exports['ps-dispatch']:CarJacking(vehicle)
end
end)
end)

**Comment by ScaryWolfies** [comment]
YES that works, you are so smart, thank you very much, btw any idea how to fix the low fuel notification ?
sorry, beginner scripter XD

**Comment by Z3R0L0G1C** [comment]
You'll need to figure out what the export or event is that your fuel script uses for setting fuel for vehicles, then call it after the vehicle is spawned on the client side.

go into zc-aitaxi/source/client/client.ts

Approx. line #: 139

 if(thisTaxi == null) {
      thisTaxi = CreateVehicle(Config[0]["TaxiCabHash"], vehicleSpawn[0], vehicleSpawn[1], vehicleSpawn[2], vehicleHeading, true, true);
//Exports['your_fuel_script'].setFuel(thisTaxi, 100); or you could put an event emitNet("fuel_script_event:server:setFuel",  thisTaxi, 100);
      } else {DebugLog("There is already a taxi Entity ID: " + thisTaxi);}

**Comment by Z3R0L0G1C** [comment]
Add me on discord if you need additional support. z3r0c00lz.

**Comment by ScaryWolfies** [comment]
not working, i figure something out, thanks anyway and thanks for the alert fix

**Comment by ScaryWolfies** [comment]
> Add me on discord if you need additional support. z3r0c00lz.

added you

**Comment by Z3R0L0G1C** [comment]
Make sure to include the period z3r0c00lz. and send me a message

**Comment by ScaryWolfies** [comment]
mine is ScaryWolfies
